from data_generator.style_transfer_generator.plotting_type.XKCD_Bar import XKCD_Bar
from data_generator.style_transfer_generator.plotting_type.XKCD_Line import XKCD_Line
from data_generator.style_transfer_generator.plotting_type.XKCD_Pie import XKCD_Pie
from data_generator.style_transfer_generator.plotting_type.XKCD_Box import XKCD_Box
from data_generator.style_transfer_generator.plotting_type.XKCD_Scatter import XKCD_Scatter

from data_generator.style_transfer_generator.opts import bar_opts, line_opts, pie_opts,box_opts, scatt_opts

import warnings
warnings.filterwarnings("ignore")

def style_transfer_base_generator(output_dir, img_dir, meta_dir, plot_number,):
    # save images generated by XKCD in temp dir

    bar_gen = XKCD_Bar(bar_opts, output_dir, img_dir, meta_dir)
    line_gen = XKCD_Line(line_opts,output_dir, img_dir, meta_dir)
    pie_gen = XKCD_Pie(pie_opts,output_dir, img_dir, meta_dir)
    box_gen = XKCD_Box(box_opts,output_dir, img_dir, meta_dir)
    scatt_gen = XKCD_Scatter(scatt_opts,output_dir, img_dir, meta_dir)


    for i in range(plot_number):
        bar_gen.plot_and_save(i)
    bar_gen.save_meta_and_dsl()
    print('Create %d base bar plot for style transfer in ./%s'%(plot_number, output_dir))

    for i in range(plot_number):
        line_gen.plot_and_save(i)
    line_gen.save_meta_and_dsl()
    print('Create %d base line plot for style transfer in ./%s' % (plot_number, output_dir))

    for i in range(plot_number):
        pie_gen.plot_and_save(i)
    pie_gen.save_meta_and_dsl()
    print('Create %d base pie plot for style transfer in ./%s'%(plot_number, output_dir))

    for i in range(plot_number):
        box_gen.plot_and_save(i)
    box_gen.save_meta_and_dsl()
    print('Create %d base box plot for style transfer plot in ./%s'%(plot_number, output_dir))

    for i in range(plot_number):
        scatt_gen.plot_and_save(i)
    scatt_gen.save_meta_and_dsl()
    print('Create %d base scat plot for style transfer in ./%s'%(plot_number, output_dir))

    print('Finished Data Generation. You can check raw data in %s' % (output_dir))